### PR TITLE
Fix application jobs getter in CronJobManager always returning empty array

### PR DESCRIPTION
**Pull request by lsimeonov**
Application jobs property have default value of `[]`. This will never pass the is_null check in its getter.

### CODE REVIEW

**Comment by lsimeonov** [comment]
What about the Application class that is used in the manager it appears that you are using `Symfony\Component\Console\Application` which is the component one and will never load the registered framework commands. Also this class is not accepting the kernel in its constructor.

Probably a mistake so I changed to the framework class `Symfony\Bundle\FrameworkBundle\Console\Application`

**Comment by nicklog** [comment]
Hey,

thank you for your support. 
You are right.

I'll take a closer look later :)

**Comment by lsimeonov** [comment]
No problem, I'm going to use your bundle in a project.
If I can help with something please say so.
If I have some time on my hands I would probably write some more tests, so we can get this covered.

Nice work on the bundle !!!

All the best from Sofia ⭐️

**Comment by nicklog** [comment]
Thank you very much.

Looks good. If you are ready, i would merge it.
Feel free to do more PR's and make suggestions for improvements.

I am open to suggestions.

best regards

**Comment by lsimeonov** [comment]
I consider adding a timestamp on the cron:run command output. I'm logging the cron in a file and this will be nice to have so you know what executed when.
You can merge this one though.

Thanks for your support!

**Comment by nicklog** [comment]
I implemented your idea.

**Pull request merged**
